#!/usr/bin/env bash
#
# sync-story-test-status.sh
#
# Detects test coverage, runs Playwright tests, and posts results to DefProd.
# Single product per invocation.
#
# Usage:
#   ./sync-story-test-status.sh --product-id <id> --api-url <url> --api-key <key> [options]
#
# Options:
#   --product-id        Product ID (or DEFPROD_PRODUCT_ID env var)
#   --api-url           API base URL, e.g. https://app.defprod.com/api/v1/rpc (or DEFPROD_API_URL)
#   --api-key           API key with read-write product scope (or DEFPROD_API_KEY)
#   --test-dir          E2E test directory (default: ./e2e/areas or DEFPROD_TEST_DIR)
#   --playwright-config Playwright config path (default: ./playwright.config.ts or DEFPROD_PLAYWRIGHT_CONFIG)
#   --area-key          Narrow scope to a single product area (e.g. CORE)
#   --env-file          Path to env file (default: .defprod.env or DEFPROD_ENV_FILE)
#   --dry-run           Print payload without posting
#   --skip-run          Check coverage only, do not run tests
#   --init              Interactive setup — creates config file
#
set -euo pipefail

# ---- Helpers ----

load_env_file() {
    local file="$1"
    while IFS= read -r line; do
        [[ -z "$line" || "$line" =~ ^# ]] && continue
        local key="${line%%=*}"
        local val="${line#*=}"
        # Strip surrounding quotes
        val="${val%\"}" ; val="${val#\"}"
        val="${val%\'}" ; val="${val#\'}"
        # Only set if not already exported (exported env vars take precedence)
        if [[ -z "${!key:-}" ]]; then
            export "$key=$val"
        fi
    done < "$file"
}

# ---- Interactive init ----

run_init() {
    echo "DefProd sync — interactive setup"
    echo "================================"
    echo ""

    read -rp "Config file location [.defprod.env]: " input_env_file
    local env_file="${input_env_file:-.defprod.env}"

    echo ""

    if [[ -f "$env_file" ]]; then
        read -rp "$env_file already exists. Overwrite? [y/N] " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 0
        fi
        echo ""
    fi

    read -rp "Product ID (from your DefProd dashboard): " input_product_id
    if [[ -z "$input_product_id" ]]; then
        echo "Error: Product ID is required." >&2
        exit 1
    fi

    read -rp "API URL [https://app.defprod.com/api/v1/rpc]: " input_api_url
    input_api_url="${input_api_url:-https://app.defprod.com/api/v1/rpc}"

    read -rp "API key (read-write product scope): " input_api_key
    if [[ -z "$input_api_key" ]]; then
        echo "Error: API key is required." >&2
        exit 1
    fi

    read -rp "E2E test directory [./e2e/areas]: " input_test_dir
    input_test_dir="${input_test_dir:-./e2e/areas}"

    read -rp "Playwright config path [./playwright.config.ts]: " input_pw_config
    input_pw_config="${input_pw_config:-./playwright.config.ts}"

    cat > "$env_file" <<EOF
# DefProd sync configuration
# Generated by: defprod-sync-tests --init

DEFPROD_PRODUCT_ID=$input_product_id
DEFPROD_API_URL=$input_api_url
DEFPROD_API_KEY=$input_api_key
DEFPROD_TEST_DIR=$input_test_dir
DEFPROD_PLAYWRIGHT_CONFIG=$input_pw_config
EOF

    echo ""
    echo "Written to $env_file"
    echo ""

    # Build the example commands with --env-file if non-default
    local env_flag=""
    if [[ "$env_file" != ".defprod.env" ]]; then
        env_flag=" --env-file $env_file"
    fi

    echo "Next steps:"
    echo "  defprod-sync-tests${env_flag} --dry-run    # preview"
    echo "  defprod-sync-tests${env_flag}              # full sync"
    echo ""
    echo "Add $env_file to your .gitignore — it contains your API key."
    exit 0
}

# ---- Load env file (before reading env vars) ----

ENV_FILE="${DEFPROD_ENV_FILE:-.defprod.env}"

# Parse --env-file and --init early (before full arg parsing)
for arg in "$@"; do
    case "$arg" in
        --init) run_init ;;
    esac
done

args=("$@")
for (( i=0; i<${#args[@]}; i++ )); do
    if [[ "${args[$i]}" == "--env-file" ]] && (( i+1 < ${#args[@]} )); then
        ENV_FILE="${args[$((i+1))]}"
        break
    fi
done

if [[ -f "$ENV_FILE" ]]; then
    load_env_file "$ENV_FILE"
fi

# ---- Configuration (CLI flags override env vars override env file) ----

PRODUCT_ID="${DEFPROD_PRODUCT_ID:-}"
API_URL="${DEFPROD_API_URL:-}"
API_KEY="${DEFPROD_API_KEY:-}"
TEST_DIR="${DEFPROD_TEST_DIR:-./e2e/areas}"
PW_CONFIG="${DEFPROD_PLAYWRIGHT_CONFIG:-./playwright.config.ts}"
AREA_KEY="${DEFPROD_AREA_KEY:-}"
DRY_RUN=false
SKIP_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --product-id)   PRODUCT_ID="$2"; shift 2 ;;
        --api-url)      API_URL="$2"; shift 2 ;;
        --api-key)      API_KEY="$2"; shift 2 ;;
        --test-dir)     TEST_DIR="$2"; shift 2 ;;
        --playwright-config) PW_CONFIG="$2"; shift 2 ;;
        --area-key)     AREA_KEY="$2"; shift 2 ;;
        --env-file)     shift 2 ;;  # already handled in early parse
        --dry-run)      DRY_RUN=true; shift ;;
        --skip-run)     SKIP_RUN=true; shift ;;
        --init)         run_init ;;
        -h|--help)      sed -n '3,21p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# Validate required args
if [[ -z "$PRODUCT_ID" ]]; then echo "Error: --product-id or DEFPROD_PRODUCT_ID required" >&2; exit 1; fi
if [[ -z "$API_URL" ]] && [[ "$DRY_RUN" == "false" ]]; then echo "Error: --api-url or DEFPROD_API_URL required" >&2; exit 1; fi
if [[ -z "$API_KEY" ]] && [[ "$DRY_RUN" == "false" ]]; then echo "Error: --api-key or DEFPROD_API_KEY required" >&2; exit 1; fi

# ---- Step 1: Fetch product definition ----

echo "Fetching product definition..."

if [[ "$DRY_RUN" == "false" ]]; then
    AREAS_JSON=$(curl -sk -X POST "$API_URL" \
        -H "Content-Type: application/json" \
        -H "x-api-key: $API_KEY" \
        -d "{\"name\":\"listAreas\",\"input\":{\"productId\":\"$PRODUCT_ID\"}}" 2>/dev/null)

    STORIES_JSON=$(curl -sk -X POST "$API_URL" \
        -H "Content-Type: application/json" \
        -H "x-api-key: $API_KEY" \
        -d "{\"name\":\"listUserStories\",\"input\":{\"productId\":\"$PRODUCT_ID\"}}" 2>/dev/null)
else
    echo "[dry-run] Skipping API calls, scanning test directory only"
    AREAS_JSON='{"data":[]}'
    STORIES_JSON='{"data":[]}'
fi

# ---- Step 2: Check coverage ----

echo "Checking test coverage in $TEST_DIR..."

AREA_KEYS=()
STATUSES_JSON="[]"
RESULTS_DIR=$(mktemp -d)
trap "rm -rf $RESULTS_DIR" EXIT

# Build story list from API response
if [[ "$DRY_RUN" == "false" ]]; then
    # Filter to single area if --area-key is set
    if [[ -n "$AREA_KEY" ]]; then
        AREAS_JSON=$(echo "$AREAS_JSON" | jq --arg key "$AREA_KEY" '{ data: [.data[] | select(.key == $key)] }')
        STORIES_JSON=$(echo "$STORIES_JSON" | jq --arg key "$AREA_KEY" '{ data: [.data[] | select(.key | startswith($key + "-"))] }')
    fi

    # Parse areas and stories from API
    AREA_COUNT=$(echo "$AREAS_JSON" | jq '.data | length')
    echo "  Found $AREA_COUNT areas"

    STORY_COUNT=$(echo "$STORIES_JSON" | jq '.data | length')
    echo "  Found $STORY_COUNT user stories"

    # Build statuses array from stories
    STATUSES_JSON=$(echo "$STORIES_JSON" | jq --arg testDir "$TEST_DIR" '
        [.data[] | {
            userStoryId: ._id,
            storyKey: .key,
            areaId: (.areaId // ""),
            areaKey: (.key | split("-")[0]),
            storyTitle: (.title // null),
            coverage: (
                if ([$testDir, (.key | split("-")[0]), .key] | join("/") | . as $dir |
                    false) then "covered" else "uncovered" end
            ),
            result: null,
            totalTests: null,
            passedTests: null,
            failedTests: null,
            flakyTests: null,
            failedTestTitles: [],
            lastRunAt: null
        }]
    ')

    # Get area keys from areas
    AREA_KEYS_JSON=$(echo "$AREAS_JSON" | jq -r '.data[].key')
    while IFS= read -r key; do
        [[ -n "$key" ]] && AREA_KEYS+=("$key")
    done <<< "$AREA_KEYS_JSON"
fi

# Override coverage by checking file system
UPDATED_STATUSES="[]"
COVERED_SPECS=()

if [[ -d "$TEST_DIR" ]]; then
    # Resolve areas root: use $TEST_DIR/areas/ if it exists, else $TEST_DIR itself
    if [[ -d "$TEST_DIR/areas" ]]; then
        AREAS_ROOT="$TEST_DIR/areas"
    else
        AREAS_ROOT="$TEST_DIR"
    fi

    # For each area directory (filtered by --area-key if set)
    for area_dir in "$AREAS_ROOT"/*/; do
        [[ -d "$area_dir" ]] || continue
        area_key=$(basename "$area_dir")
        [[ -n "$AREA_KEY" ]] && [[ "$area_key" != "$AREA_KEY" ]] && continue

        # For each story directory
        for story_dir in "$area_dir"*/; do
            [[ -d "$story_dir" ]] || continue
            story_key=$(basename "$story_dir")

            # Check for spec files
            spec_count=$(find "$story_dir" -name "*.spec.ts" 2>/dev/null | wc -l)
            if [[ "$spec_count" -gt 0 ]]; then
                COVERED_SPECS+=("$area_key/$story_key")
            fi
        done
    done
fi

echo "  Covered stories: ${#COVERED_SPECS[@]}"

# Update statuses with coverage info from file system
if [[ "$DRY_RUN" == "false" ]]; then
    COVERED_LIST=$(printf '%s\n' "${COVERED_SPECS[@]:-}" | jq -R . | jq -s .)
    STATUSES_JSON=$(echo "$STATUSES_JSON" | jq --argjson covered "$COVERED_LIST" '
        [.[] | . as $s |
            ($s.areaKey + "/" + $s.storyKey) as $path |
            if ($covered | index($path)) then
                .coverage = "covered"
            else
                .coverage = "uncovered"
            end
        ]
    ')
fi

# ---- Step 3: Run tests (if not --skip-run) ----

if [[ "$SKIP_RUN" == "false" ]] && [[ ${#COVERED_SPECS[@]} -gt 0 ]]; then
    echo "Running Playwright tests..."

    PW_JSON_REPORT="$RESULTS_DIR/results.json"

    # Build grep pattern for covered specs
    SPEC_PATTERN=$(printf '%s\n' "${COVERED_SPECS[@]}" | sed 's|/|/|g' | paste -sd '|' -)

    # Run Playwright with JSON reporter
    PLAYWRIGHT_JSON_OUTPUT_FILE="$PW_JSON_REPORT" \
        npx playwright test \
        --config="$PW_CONFIG" \
        --reporter=json \
        --grep="$SPEC_PATTERN" \
        "$TEST_DIR" 2>/dev/null || true

    # Parse results if JSON report exists
    if [[ -f "$PW_JSON_REPORT" ]]; then
        echo "  Parsing test results..."

        # Extract per-spec results
        STATUSES_JSON=$(echo "$STATUSES_JSON" | jq --slurpfile results "$PW_JSON_REPORT" '
            ($results[0].suites // []) as $suites |

            # Flatten all specs from suites
            [($suites[] | .. | .specs? // empty | .[]) |
                {
                    file: .file,
                    title: .title,
                    ok: .ok,
                    tests: [.tests[] | {
                        status: .status,
                        results: [.results[] | .status]
                    }]
                }
            ] as $allSpecs |

            [.[] | . as $status |
                ($status.areaKey + "/" + $status.storyKey) as $storyPath |

                # Find matching specs for this story
                [$allSpecs[] | select(.file | contains($storyPath))] as $matchingSpecs |

                if ($matchingSpecs | length) > 0 then
                    # Compute totals
                    ($matchingSpecs | length) as $total |
                    ([$matchingSpecs[] | select(.ok == true)] | length) as $passed |
                    ([$matchingSpecs[] | select(.ok == false) | select(.tests | any(.results | any(. == "flaky")))] | length) as $flaky |
                    ($total - $passed - $flaky) as $failed |

                    # Determine result
                    (if $failed > 0 then "failing"
                     elif $flaky > 0 then "flaky"
                     else "passing" end) as $result |

                    # Failed test titles
                    ([$matchingSpecs[] | select(.ok == false) | .title]) as $failedTitles |

                    .result = $result |
                    .totalTests = $total |
                    .passedTests = $passed |
                    .failedTests = $failed |
                    .flakyTests = $flaky |
                    .failedTestTitles = $failedTitles |
                    .lastRunAt = (now | todate)
                else
                    .
                end
            ]
        ')
    else
        echo "  No JSON report generated"
    fi
elif [[ "$SKIP_RUN" == "true" ]]; then
    echo "Skipping test run (--skip-run)"
else
    echo "No covered stories — skipping test run"
fi

# ---- Step 4: Build and post payload ----

AREA_KEYS_ARRAY=$(printf '%s\n' "${AREA_KEYS[@]:-}" | jq -R . | jq -s .)

PAYLOAD=$(jq -n \
    --arg productId "$PRODUCT_ID" \
    --argjson areaKeys "$AREA_KEYS_ARRAY" \
    --argjson statuses "$STATUSES_JSON" \
    '{
        name: "syncStoryTestStatus",
        input: {
            productId: $productId,
            areaKeys: $areaKeys,
            statuses: $statuses
        }
    }')

if [[ "$DRY_RUN" == "true" ]]; then
    echo ""
    echo "=== DRY RUN — payload ==="
    echo "$PAYLOAD" | jq .
    exit 0
fi

echo "Posting results to DefProd..."

RESPONSE=$(curl -sk -X POST "$API_URL" \
    -H "Content-Type: application/json" \
    -H "x-api-key: $API_KEY" \
    -d "$PAYLOAD" 2>/dev/null)

UPSERTED=$(echo "$RESPONSE" | jq -r '.data.upsertedCount // "?"')
DELETED=$(echo "$RESPONSE" | jq -r '.data.deletedCount // "?"')
ERROR=$(echo "$RESPONSE" | jq -r '.meta.error // false')

if [[ "$ERROR" == "true" ]]; then
    echo "Error: $(echo "$RESPONSE" | jq -r '.error.details // .error.title // "unknown"')" >&2
    exit 1
fi

echo "Done. Upserted: $UPSERTED, Deleted: $DELETED"
