#!/usr/bin/env bash
#
# sync-story-test-status.sh
#
# Detects test coverage, runs tests (Playwright + Vitest + Jest), and posts
# per-story results to DefProd. Single product per invocation. Multi-suite
# mode lets one run cover Playwright e2e + non-UI integration harnesses
# (REST API, MCP, CLI) in a single payload.
#
# Usage:
#   ./sync-story-test-status.sh --product-id <id> --api-url <url> --api-key <key> [options]
#
# Options:
#   --product-id        Product ID (or DEFPROD_PRODUCT_ID env var)
#   --api-url           API base URL, e.g. https://app.defprod.com/api/v1/rpc (or DEFPROD_API_URL)
#   --api-key           API key with read-write product scope (or DEFPROD_API_KEY)
#   --test-dir          Single-suite mode: test directory (default ./e2e/areas or DEFPROD_TEST_DIR)
#   --playwright-config Single-suite mode: Playwright config (default ./playwright.config.ts)
#   --project           Playwright project(s) to run, comma-separated (default 'chromium',
#                       or DEFPROD_PLAYWRIGHT_PROJECTS). Set empty to run every project the
#                       Playwright config declares.
#   --test-suites       Multi-suite mode: ';'-separated list of 'harness:dir:config' entries.
#                       harness is one of 'playwright', 'vitest', 'jest'.
#                       Overrides --test-dir and --playwright-config when set.
#                       Also readable from DEFPROD_TEST_SUITES env var.
#   --area-key          Narrow scope to a single product area (e.g. CORE)
#   --env-file          Path to env file (default: .defprod.env or DEFPROD_ENV_FILE)
#   --dry-run           Print payload without posting
#   --skip-run          Check coverage only, do not run tests
#   --init              Interactive setup — creates config file
#   --version, -v       Print version and exit
#
set -euo pipefail

# ---- Helpers ----

VERSION="dev" # baked by prepublish

load_env_file() {
    local file="$1"
    while IFS= read -r line; do
        [[ -z "$line" || "$line" =~ ^# ]] && continue
        local key="${line%%=*}"
        local val="${line#*=}"
        # Strip surrounding quotes
        val="${val%\"}" ; val="${val#\"}"
        val="${val%\'}" ; val="${val#\'}"
        # Only set if not already exported (exported env vars take precedence)
        if [[ -z "${!key:-}" ]]; then
            export "$key=$val"
        fi
    done < "$file"
}

# ---- Interactive init ----

run_init() {
    echo "DefProd sync — interactive setup"
    echo "================================"
    echo ""

    read -rp "Config file location [.defprod.env]: " input_env_file
    local env_file="${input_env_file:-.defprod.env}"

    echo ""

    if [[ -f "$env_file" ]]; then
        read -rp "$env_file already exists. Overwrite? [y/N] " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 0
        fi
        echo ""
    fi

    read -rp "Product ID (from your DefProd dashboard): " input_product_id
    if [[ -z "$input_product_id" ]]; then
        echo "Error: Product ID is required." >&2
        exit 1
    fi

    read -rp "API URL [https://app.defprod.com/api/v1/rpc]: " input_api_url
    input_api_url="${input_api_url:-https://app.defprod.com/api/v1/rpc}"

    read -rp "API key (read-write product scope): " input_api_key
    if [[ -z "$input_api_key" ]]; then
        echo "Error: API key is required." >&2
        exit 1
    fi

    read -rp "E2E test directory [./e2e/areas]: " input_test_dir
    input_test_dir="${input_test_dir:-./e2e/areas}"

    read -rp "Playwright config path [./playwright.config.ts]: " input_pw_config
    input_pw_config="${input_pw_config:-./playwright.config.ts}"

    read -rp "Playwright projects (comma-separated) [chromium]: " input_pw_projects
    input_pw_projects="${input_pw_projects:-chromium}"

    cat > "$env_file" <<EOF
# DefProd sync configuration
# Generated by: defprod-sync-tests --init

DEFPROD_PRODUCT_ID=$input_product_id
DEFPROD_API_URL=$input_api_url
DEFPROD_API_KEY=$input_api_key
DEFPROD_TEST_DIR=$input_test_dir
DEFPROD_PLAYWRIGHT_CONFIG=$input_pw_config
DEFPROD_PLAYWRIGHT_PROJECTS=$input_pw_projects

# Multi-suite mode (optional). When set, overrides DEFPROD_TEST_DIR
# and DEFPROD_PLAYWRIGHT_CONFIG. Format:
#   harness:dir:config[;harness:dir:config...]
# Example covering Playwright e2e + Vitest API + Vitest MCP + Jest CLI:
# DEFPROD_TEST_SUITES=playwright:apps/defprod-front/e2e:apps/defprod-front/playwright.config.ts;vitest:apps/defprod-back/tests/areas:apps/defprod-back/vitest.config.api.ts;vitest:apps/defprod-mcp/tests/areas:apps/defprod-mcp/vitest.config.mcp.ts;jest:apps/defprod-cli/tests/areas:apps/defprod-cli/jest.config.areas.ts
EOF

    echo ""
    echo "Written to $env_file"
    echo ""

    # Build the example commands with --env-file if non-default
    local env_flag=""
    if [[ "$env_file" != ".defprod.env" ]]; then
        env_flag=" --env-file $env_file"
    fi

    echo "Next steps:"
    echo "  defprod-sync-tests${env_flag} --dry-run    # preview"
    echo "  defprod-sync-tests${env_flag}              # full sync"
    echo ""
    echo "Add $env_file to your .gitignore — it contains your API key."
    exit 0
}

# ---- Load env file (before reading env vars) ----

ENV_FILE="${DEFPROD_ENV_FILE:-.defprod.env}"

# Parse --env-file, --init, and --version early (before full arg parsing)
for arg in "$@"; do
    case "$arg" in
        --init) run_init ;;
        --version|-v) echo "defprod-sync-tests $VERSION"; exit 0 ;;
    esac
done

args=("$@")
for (( i=0; i<${#args[@]}; i++ )); do
    if [[ "${args[$i]}" == "--env-file" ]] && (( i+1 < ${#args[@]} )); then
        ENV_FILE="${args[$((i+1))]}"
        break
    fi
done

if [[ -f "$ENV_FILE" ]]; then
    load_env_file "$ENV_FILE"
fi

# ---- Configuration (CLI flags override env vars override env file) ----

PRODUCT_ID="${DEFPROD_PRODUCT_ID:-}"
API_URL="${DEFPROD_API_URL:-}"
API_KEY="${DEFPROD_API_KEY:-}"
TEST_DIR="${DEFPROD_TEST_DIR:-./e2e/areas}"
PW_CONFIG="${DEFPROD_PLAYWRIGHT_CONFIG:-./playwright.config.ts}"
# Playwright project(s) to run. Comma-separated list — each value becomes a
# --project= flag. Defaults to 'chromium' so a stock dev machine does not
# try to launch firefox/webkit binaries it has never installed. Set to ''
# (empty) to fall back to Playwright's own default (every project the
# config declares).
PW_PROJECTS="${DEFPROD_PLAYWRIGHT_PROJECTS-chromium}"
TEST_SUITES_RAW="${DEFPROD_TEST_SUITES:-}"
AREA_KEY="${DEFPROD_AREA_KEY:-}"
DRY_RUN=false
SKIP_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --product-id)   PRODUCT_ID="$2"; shift 2 ;;
        --api-url)      API_URL="$2"; shift 2 ;;
        --api-key)      API_KEY="$2"; shift 2 ;;
        --test-dir)     TEST_DIR="$2"; shift 2 ;;
        --playwright-config) PW_CONFIG="$2"; shift 2 ;;
        --project)      PW_PROJECTS="$2"; shift 2 ;;
        --test-suites)  TEST_SUITES_RAW="$2"; shift 2 ;;
        --area-key)     AREA_KEY="$2"; shift 2 ;;
        --env-file)     shift 2 ;;  # already handled in early parse
        --dry-run)      DRY_RUN=true; shift ;;
        --skip-run)     SKIP_RUN=true; shift ;;
        --init)         run_init ;;
        --version|-v)   echo "defprod-sync-tests $VERSION"; exit 0 ;;
        -h|--help)      sed -n '3,32p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# Validate required args
if [[ -z "$PRODUCT_ID" ]]; then echo "Error: --product-id or DEFPROD_PRODUCT_ID required" >&2; exit 1; fi
if [[ -z "$API_URL" ]]; then echo "Error: --api-url or DEFPROD_API_URL required" >&2; exit 1; fi
if [[ -z "$API_KEY" ]]; then echo "Error: --api-key or DEFPROD_API_KEY required" >&2; exit 1; fi

# ---- Resolve suites list ----

declare -a TEST_SUITES
if [[ -n "$TEST_SUITES_RAW" ]]; then
    IFS=';' read -ra TEST_SUITES <<< "$TEST_SUITES_RAW"
else
    # Back-compat: single Playwright suite from --test-dir / --playwright-config
    TEST_SUITES=("playwright:${TEST_DIR}:${PW_CONFIG}")
fi

# ---- Step 1: Fetch product definition ----

echo "Fetching product definition..."

# Read-only API calls run in all modes (including --dry-run); only the
# write (syncStoryTestStatus) is suppressed by --dry-run.
AREAS_JSON=$(curl -sk -X POST "$API_URL" \
    -H "Content-Type: application/json" \
    -H "x-api-key: $API_KEY" \
    -d "{\"name\":\"listAreas\",\"input\":{\"productId\":\"$PRODUCT_ID\"}}" 2>/dev/null)

STORIES_JSON=$(curl -sk -X POST "$API_URL" \
    -H "Content-Type: application/json" \
    -H "x-api-key: $API_KEY" \
    -d "{\"name\":\"listUserStories\",\"input\":{\"productId\":\"$PRODUCT_ID\"}}" 2>/dev/null)

# Filter to single area if --area-key is set
if [[ -n "$AREA_KEY" ]]; then
    AREAS_JSON=$(echo "$AREAS_JSON" | jq --arg key "$AREA_KEY" '{ data: [.data[] | select(.key == $key)] }')
    STORIES_JSON=$(echo "$STORIES_JSON" | jq --arg key "$AREA_KEY" '{ data: [.data[] | select(.key | startswith($key + "-"))] }')
fi

AREA_COUNT=$(echo "$AREAS_JSON" | jq '.data | length')
STORY_COUNT=$(echo "$STORIES_JSON" | jq '.data | length')
echo "  Found $AREA_COUNT areas / $STORY_COUNT user stories"

AREA_KEYS=()
while IFS= read -r key; do
    [[ -n "$key" ]] && AREA_KEYS+=("$key")
done < <(echo "$AREAS_JSON" | jq -r '.data[].key')

# ---- Working state ----

RESULTS_DIR=$(mktemp -d)
trap "rm -rf $RESULTS_DIR" EXIT

# Per-story result accumulator. One entry per (storyKey) that any suite ran.
# Written incrementally to $RESULTS_DIR/per-story-results.json as
# {areaKey, storyKey, totalTests, passedTests, failedTests, flakyTests, skippedTests, failedTestTitles, lastRunAt}.
echo "[]" > "$RESULTS_DIR/per-story-results.json"

# Coverage accumulator: jq-set of "<areaKey>/<storyKey>" paths covered by ANY suite.
echo "[]" > "$RESULTS_DIR/covered-paths.json"

# ---- Per-suite helpers ----

# walk_suite_coverage <harness> <dir>
# Echoes "<areaKey>/<storyKey>" lines for every story dir under <dir>/[areas/]
# that contains at least one matching test file.
walk_suite_coverage() {
    local harness="$1"
    local dir="$2"
    local glob

    case "$harness" in
        playwright) glob="*.spec.ts" ;;
        vitest|jest) glob="*.test.ts" ;;
        *) echo "ERROR: unknown harness '$harness'" >&2; return 1 ;;
    esac

    [[ -d "$dir" ]] || return 0

    # Resolve areas root: <dir>/areas/ if present, else <dir> itself.
    local areas_root="$dir"
    [[ -d "$dir/areas" ]] && areas_root="$dir/areas"

    for area_dir in "$areas_root"/*/; do
        [[ -d "$area_dir" ]] || continue
        local area_key
        area_key=$(basename "$area_dir")
        [[ -n "$AREA_KEY" ]] && [[ "$area_key" != "$AREA_KEY" ]] && continue

        for story_dir in "$area_dir"*/; do
            [[ -d "$story_dir" ]] || continue
            local story_key
            story_key=$(basename "$story_dir")
            local count
            count=$(find "$story_dir" -name "$glob" 2>/dev/null | wc -l)
            if [[ "$count" -gt 0 ]]; then
                echo "$area_key/$story_key"
            fi
        done
    done
}

# run_playwright_suite <dir> <config> <covered_specs_list_file> <output_json>
run_playwright_suite() {
    local dir="$1"
    local config="$2"
    local covered_file="$3"
    local out_json="$4"

    local config_abs config_dir
    config_abs=$(cd "$(dirname "$config")" && pwd)/$(basename "$config")
    config_dir=$(dirname "$config_abs")

    # Prefer package-local playwright to avoid dual-instance errors.
    local pw_cmd=()
    if [[ -x "$config_dir/node_modules/.bin/playwright" ]]; then
        pw_cmd=("$config_dir/node_modules/.bin/playwright")
    elif [[ -f "$config_dir/node_modules/playwright/cli.js" ]]; then
        pw_cmd=(node "$config_dir/node_modules/playwright/cli.js")
    else
        pw_cmd=(npx playwright)
    fi

    # Resolve covered specs back to absolute story dirs to pass as positional args.
    local areas_root="$dir"
    [[ -d "$dir/areas" ]] && areas_root="$dir/areas"

    local spec_dirs=()
    while IFS= read -r covered; do
        [[ -z "$covered" ]] && continue
        spec_dirs+=("$(cd "$areas_root/$covered" && pwd)")
    done < "$covered_file"

    # Build --project= flags from PW_PROJECTS (comma-separated). When empty,
    # we pass no --project flag and Playwright uses every project the config
    # declares (historical behaviour). The default 'chromium' value avoids
    # tripping over firefox/webkit binaries on dev machines that never
    # installed them.
    local project_flags=()
    if [[ -n "${PW_PROJECTS:-}" ]]; then
        local _p
        local IFS_BAK="$IFS"; IFS=','
        for _p in $PW_PROJECTS; do
            _p="${_p// /}"
            [[ -n "$_p" ]] && project_flags+=("--project=$_p")
        done
        IFS="$IFS_BAK"
        echo "  Playwright projects: $PW_PROJECTS"
    else
        echo "  Playwright projects: <all from config>"
    fi

    # Run with JSON reporter. Capture stderr so we can detect a missing
    # browser binary before parsing — otherwise the missing-binary error
    # surfaces as 'unexpected' per project and flips every story to
    # 'failing' for a tooling reason rather than a real defect.
    local pw_stderr_file
    pw_stderr_file=$(dirname "$out_json")/playwright-suite.stderr
    PLAYWRIGHT_JSON_OUTPUT_FILE="$out_json" \
        "${pw_cmd[@]}" test \
        --config="$config_abs" \
        --reporter=json \
        "${project_flags[@]}" \
        "${spec_dirs[@]}" 2>"$pw_stderr_file" || true

    # Abort before posting if any browser binary is missing. Treat this as
    # fatal regardless of --dry-run so a dry run accurately reflects what a
    # real run would do.
    if [[ -f "$pw_stderr_file" ]] && grep -q "browserType.launch: Executable doesn't exist" "$pw_stderr_file" 2>/dev/null; then
        local missing
        missing=$(grep -oE "ms-playwright/(firefox|webkit|chromium)[^/]*" "$pw_stderr_file" \
                  | grep -oE "(firefox|webkit|chromium)" \
                  | sort -u | tr '\n' ' ' | sed 's/ $//')
        echo "" >&2
        echo "Error: Playwright browser binaries are not installed: $missing" >&2
        echo "  Fix one:" >&2
        echo "    1) npx playwright install $missing" >&2
        echo "    2) Or set DEFPROD_PLAYWRIGHT_PROJECTS to a browser you have installed (e.g. chromium)." >&2
        echo "" >&2
        echo "Aborting before posting — partial results would corrupt DefProd state." >&2
        exit 1
    fi
}

# parse_playwright_results <results_json> <areas_root>
# Reads the Playwright JSON reporter output and emits per-story status objects
# (one JSON array on stdout) matching the per-story-results.json schema.
parse_playwright_results() {
    local results_json="$1"
    local areas_root="$2"

    [[ -f "$results_json" ]] || { echo "[]"; return 0; }

    jq --slurpfile r "$results_json" --arg areasRoot "$areas_root" '
        # Collect every spec.
        ($r[0].suites // []) as $suites |
        [($suites[] | .. | .specs? // empty | .[]) |
            {
                file: .file,
                title: .title,
                tests: [.tests[] | {
                    status: .status,
                    results: [.results[] | .status]
                }]
            }
        ] as $allSpecs |

        # Group specs by inferred (areaKey, storyKey) from path segments.
        # Spec file paths look like .../areas/<AREA>/<STORY-KEY>/<name>.spec.ts
        # or .../<AREA>/<STORY-KEY>/<name>.spec.ts (no /areas/).
        [$allSpecs[] |
            # Story keys may have multiple dash-segments (e.g. CORE-MOB-10) —
            # use a non-greedy quantifier on the dash-segment so the trailing
            # /<file>.spec.ts portion can still be matched.
            (.file | capture("/(?<areaKey>[A-Z0-9_]+)/(?<storyKey>[A-Z0-9_]+(?:-[A-Z0-9_]+)+)/[^/]+\\.spec\\.ts$")) as $m |
            select($m != null) |
            . + { areaKey: $m.areaKey, storyKey: $m.storyKey }
        ] |
        group_by(.areaKey + "/" + .storyKey) |
        [.[] |
            (.[0].areaKey) as $areaKey | (.[0].storyKey) as $storyKey |

            # Deduplicate by title across browser projects.
            (group_by(.title) | [.[] |
                [.[].tests[]] as $allTests |
                ([$allTests[] | select(.status != "skipped")] | length) as $ranCount |
                {
                    title: .[0].title,
                    failed: ([$allTests[] | select(.status == "unexpected")] | length > 0),
                    flaky: ([$allTests[] | .results[] | select(. == "flaky")] | length > 0),
                    skippedOnly: ($ranCount == 0)
                }
            ]) as $dedupedSpecs |

            ([$dedupedSpecs[] | select(.skippedOnly | not)]) as $activeSpecs |
            ([$dedupedSpecs[] | select(.skippedOnly)])     as $skippedSpecs |

            ($activeSpecs | length) as $total |
            ([$activeSpecs[] | select(.failed | not)] | length) as $passed |
            ([$activeSpecs[] | select(.failed) | select(.flaky)] | length) as $flaky |
            ($total - $passed - $flaky) as $failed |
            ($skippedSpecs | length) as $skipped |

            (if $failed > 0 then "failing"
             elif $flaky > 0 then "flaky"
             else "passing" end) as $result |

            ([$activeSpecs[] | select(.failed) | .title] | unique) as $failedTitles |

            {
                areaKey: $areaKey,
                storyKey: $storyKey,
                result: $result,
                totalTests: $total,
                passedTests: $passed,
                failedTests: $failed,
                flakyTests: $flaky,
                skippedTests: $skipped,
                failedTestTitles: $failedTitles,
                lastRunAt: (now | todate)
            }
        ]
    ' <<< '{}'
}

# run_vitest_suite <dir> <config> <output_json>
run_vitest_suite() {
    local dir="$1"
    local config="$2"
    local out_json="$3"

    local config_abs
    config_abs=$(cd "$(dirname "$config")" && pwd)/$(basename "$config")

    npx vitest run -c "$config_abs" --reporter=json --outputFile="$out_json" "$dir" 2>/dev/null || true
}

# run_jest_suite <dir> <config> <output_json>
run_jest_suite() {
    local dir="$1"
    local config="$2"
    local out_json="$3"

    local config_abs
    config_abs=$(cd "$(dirname "$config")" && pwd)/$(basename "$config")

    npx jest --config="$config_abs" --json --outputFile="$out_json" "$dir" 2>/dev/null || true
}

# parse_jest_compat_results <results_json>
# Vitest's JSON reporter is Jest-compatible. Both produce { testResults: [
#   { name: <spec.test.ts path>, status, assertionResults: [ {title, fullName, status, ...} ] }
# ]}.
parse_jest_compat_results() {
    local results_json="$1"

    [[ -f "$results_json" ]] || { echo "[]"; return 0; }

    jq --slurpfile r "$results_json" '
        ($r[0].testResults // []) as $files |

        # For each spec file: extract (areaKey, storyKey) from the path.
        # Path looks like .../areas/<AREA>/<STORY-KEY>/<name>.test.ts
        # or .../<AREA>/<STORY-KEY>/<name>.test.ts.
        [$files[] |
            # Story keys may have multiple dash-segments (e.g. CORE-MOB-10).
            (.name | capture("/(?<areaKey>[A-Z0-9_]+)/(?<storyKey>[A-Z0-9_]+(?:-[A-Z0-9_]+)+)/[^/]+\\.test\\.ts$")) as $m |
            select($m != null) |
            {
                areaKey: $m.areaKey,
                storyKey: $m.storyKey,
                tests: (.assertionResults // [])
            }
        ] |

        # Group by (areaKey, storyKey) — handles the case where a story has
        # multiple spec files (rare, but possible).
        group_by(.areaKey + "/" + .storyKey) |

        [.[] |
            (.[0].areaKey) as $areaKey |
            (.[0].storyKey) as $storyKey |
            ([.[] | .tests[]]) as $allTests |

            ($allTests | length) as $total |
            ([$allTests[] | select(.status == "passed")] | length) as $passed |
            ([$allTests[] | select(.status == "failed")] | length) as $failed |
            ([$allTests[] | select(.status == "pending" or .status == "skipped" or .status == "todo")] | length) as $skipped |

            # Vitest/Jest do not have a native "flaky" concept; report 0.
            0 as $flaky |

            # The backend TestResult enum is passing|failing|flaky only.
            # All-skipped stories map to null (no usable result), not the
            # placeholder string "no-run" (which the backend rejects with
            # "Invalid Request").
            (if $failed > 0 then "failing"
             elif $passed > 0 then "passing"
             else null end) as $result |

            ([$allTests[] | select(.status == "failed") | .title] | unique) as $failedTitles |

            {
                areaKey: $areaKey,
                storyKey: $storyKey,
                result: $result,
                totalTests: $total,
                passedTests: $passed,
                failedTests: $failed,
                flakyTests: $flaky,
                skippedTests: $skipped,
                failedTestTitles: $failedTitles,
                lastRunAt: (now | todate)
            }
        ]
    ' <<< '{}'
}

# ---- Step 2 + 3: per-suite coverage + run + parse ----

for suite_spec in "${TEST_SUITES[@]}"; do
    IFS=':' read -r suite_harness suite_dir suite_config <<< "$suite_spec"
    echo ""
    echo "Suite: $suite_harness  $suite_dir"

    # Collect this suite's covered <areaKey>/<storyKey> list.
    suite_covered_file="$RESULTS_DIR/${suite_harness}-covered.txt"
    walk_suite_coverage "$suite_harness" "$suite_dir" > "$suite_covered_file"
    suite_count=$(wc -l < "$suite_covered_file" | tr -d ' ')
    echo "  Covered stories: $suite_count"

    # Merge into global covered set.
    if [[ "$suite_count" -gt 0 ]]; then
        jq --rawfile new "$suite_covered_file" '
            . as $existing |
            ($new | split("\n") | map(select(length > 0))) as $added |
            ($existing + $added | unique)
        ' "$RESULTS_DIR/covered-paths.json" > "$RESULTS_DIR/covered-paths.json.tmp" && \
        mv "$RESULTS_DIR/covered-paths.json.tmp" "$RESULTS_DIR/covered-paths.json"
    fi

    # Skip the run if requested or nothing to run.
    [[ "$SKIP_RUN" == "true" ]] && continue
    [[ "$suite_count" -eq 0 ]] && continue

    suite_results_raw="$RESULTS_DIR/${suite_harness}-raw.json"
    suite_results_parsed="$RESULTS_DIR/${suite_harness}-parsed.json"

    case "$suite_harness" in
        playwright)
            echo "  Running Playwright..."
            run_playwright_suite "$suite_dir" "$suite_config" "$suite_covered_file" "$suite_results_raw"
            areas_root="$suite_dir"
            [[ -d "$suite_dir/areas" ]] && areas_root="$suite_dir/areas"
            parse_playwright_results "$suite_results_raw" "$areas_root" > "$suite_results_parsed"
            ;;
        vitest)
            echo "  Running Vitest..."
            run_vitest_suite "$suite_dir" "$suite_config" "$suite_results_raw"
            parse_jest_compat_results "$suite_results_raw" > "$suite_results_parsed"
            ;;
        jest)
            echo "  Running Jest..."
            run_jest_suite "$suite_dir" "$suite_config" "$suite_results_raw"
            parse_jest_compat_results "$suite_results_raw" > "$suite_results_parsed"
            ;;
        *)
            echo "  Unknown harness — skipping" >&2
            continue
            ;;
    esac

    parsed_count=$(jq 'length' "$suite_results_parsed")
    echo "  Parsed results for $parsed_count stories"

    # Merge into the global per-story results accumulator. If a story already
    # has a result, keep the existing one (suites are expected to cover disjoint
    # areas; first-wins is the safer rule).
    #
    # NOTE: bind (areaKey + "/" + storyKey) to $k BEFORE the index() call —
    # inside `index(...)` the value expression is re-evaluated against
    # $existingKeys (an array), which would throw "Cannot index array with
    # string 'storyKey'".
    jq --slurpfile new "$suite_results_parsed" '
        . as $existing |
        $new[0] as $added |
        ($existing | map(.areaKey + "/" + .storyKey)) as $existingKeys |
        $existing + [$added[] |
            (.areaKey + "/" + .storyKey) as $k |
            select(($existingKeys | index($k)) | not)
        ]
    ' "$RESULTS_DIR/per-story-results.json" > "$RESULTS_DIR/per-story-results.json.tmp" && \
    mv "$RESULTS_DIR/per-story-results.json.tmp" "$RESULTS_DIR/per-story-results.json"
done

# ---- Step 4: Build per-story statuses array ----

# Start from the API story list, then enrich each story with coverage + result.
STATUSES_FILE="$RESULTS_DIR/statuses.json"
echo "$STORIES_JSON" | jq \
    --slurpfile covered "$RESULTS_DIR/covered-paths.json" \
    --slurpfile results "$RESULTS_DIR/per-story-results.json" '
    [.data[] |
        . as $story |
        ($story.key | split("-")[0]) as $areaKey |
        ($areaKey + "/" + $story.key) as $path |
        ([$results[0][] | select(.areaKey == $areaKey and .storyKey == $story.key)] | first) as $r |
        ({
            userStoryId: $story._id,
            storyKey: $story.key,
            areaId: ($story.areaId // ""),
            areaKey: $areaKey,
            storyTitle: ($story.title // null),
            coverage: (if ($covered[0] | index($path)) then "covered" else "uncovered" end),
            result: null,
            totalTests: null,
            passedTests: null,
            failedTests: null,
            flakyTests: null,
            skippedTests: null,
            failedTestTitles: [],
            lastRunAt: null
        }) | if $r != null then
            . + {
                result: $r.result,
                totalTests: $r.totalTests,
                passedTests: $r.passedTests,
                failedTests: $r.failedTests,
                flakyTests: $r.flakyTests,
                skippedTests: $r.skippedTests,
                failedTestTitles: $r.failedTestTitles,
                lastRunAt: $r.lastRunAt
            }
        else . end
    ]' > "$STATUSES_FILE"

echo ""
echo "Per-story summary:"
jq -r '.[] | "  \(.storyKey): \(.coverage) / \(.result // "no-run") \(.passedTests // "-")/\(.totalTests // "-") \(if (.failedTestTitles | length) > 0 then "FAILED: " + (.failedTestTitles | join(", ")) else "" end)"' "$STATUSES_FILE"

# ---- Step 5: Build and post payload ----

AREA_KEYS_ARRAY=$(printf '%s\n' "${AREA_KEYS[@]:-}" | jq -R . | jq -s .)

PAYLOAD_FILE="$RESULTS_DIR/payload.json"
jq -n \
    --arg productId "$PRODUCT_ID" \
    --argjson areaKeys "$AREA_KEYS_ARRAY" \
    --slurpfile statuses "$STATUSES_FILE" \
    '{
        name: "syncStoryTestStatus",
        input: {
            productId: $productId,
            areaKeys: $areaKeys,
            statuses: $statuses[0]
        }
    }' > "$PAYLOAD_FILE"

if [[ "$DRY_RUN" == "true" ]]; then
    echo ""
    echo "=== DRY RUN — payload ==="
    jq . "$PAYLOAD_FILE"
    exit 0
fi

echo ""
echo "Posting results to DefProd..."

RESPONSE=$(curl -sk -X POST "$API_URL" \
    -H "Content-Type: application/json" \
    -H "x-api-key: $API_KEY" \
    -d "@$PAYLOAD_FILE" 2>/dev/null)

UPSERTED=$(echo "$RESPONSE" | jq -r '.data.upsertedCount // "?"')
DELETED=$(echo "$RESPONSE" | jq -r '.data.deletedCount // "?"')
ERROR=$(echo "$RESPONSE" | jq -r '.meta.error // false')

if [[ "$ERROR" == "true" ]]; then
    echo "Error: $(echo "$RESPONSE" | jq -r '.error.details // .error.title // "unknown"')" >&2
    exit 1
fi

echo "Done. Upserted: $UPSERTED, Deleted: $DELETED"
